### PR TITLE
Feature/version information

### LINKED ISSUE #9: Version information and detailed optimizer parameters should be part of the response
For debugging and documentation purposes as detailed information as possible about the current optimizer run should be part of the response.

Things to include:

- ProcessOptimizer version
- API version (git tag of this project)
- ProcessOptimizer parameters
- Time of run

### PR DESCRIPTION
**Pull request by langdal**
### Summary

This PR adds various meta data to the response json produced by the API server.

- Version information for all dependencies used in the API
- Hyperparams
- All data points and their definitions
- Extra run parameters send as part of the run request
- Date and time of execution
- Version information for the API server

Closes #9 

### Notes

The README is updated with procedures that need to be followed when adding or updating **requirements,txt**
Also ProcessOptimizer is updated to version 0.7.1

### Example of the data returned to clients

```json
 "extras": {
      "apiVersion": "v1.0.0-18-gdadd7fc",
      "libraries": [
        "attrs==20.3.0",
        "bokeh==2.2.3",
        "certifi==2020.12.5",
        "cffi==1.14.5",
        "chardet==4.0.0",
        "click==7.1.2",
        "clickclick==20.10.2",
        "colorama==0.4.4",
        "connexion==2.7.0",
        "cryptography==3.4.7",
        "cycler==0.10.0",
        "deap==1.3.1",
        "docopt==0.6.2",
        "Flask==1.1.2",
        "idna==2.10",
        "inflection==0.5.1",
        "iniconfig==1.1.1",
        "itsdangerous==1.1.0",
        "Jinja2==2.11.3",
        "joblib==1.0.1",
        "json-tricks==3.15.5",
        "jsonschema==3.2.0",
        "kiwisolver==1.3.1",
        "MarkupSafe==1.1.1",
        "matplotlib==3.3.4",
        "numpy==1.20.1",
        "openapi-spec-validator==0.2.9",
        "packaging==20.9",
        "Pillow==8.1.0",
        "pkg_resources==0.0.0",
        "pluggy==0.13.1",
        "ProcessOptimizer==0.7.1",
        "py==1.10.0",
        "pycparser==2.20",
        "pyparsing==2.4.7",
        "pyrsistent==0.17.3",
        "pytest==6.2.2",
        "pytest-watch==4.2.0",
        "python-dateutil==2.8.1",
        "PyYAML==5.4.1",
        "requests==2.25.1",
        "scikit-learn==0.24.2",
        "scipy==1.6.0",
        "six==1.15.0",
        "swagger-ui-bundle==0.0.8",
        "threadpoolctl==2.1.0",
        "toml==0.10.2",
        "tornado==6.1",
        "typing-extensions==3.7.4.3",
        "urllib3==1.26.3",
        "waitress==2.0.0",
        "watchdog==2.0.2",
        "Werkzeug==1.0.1"
      ],
      "parameters": {
        "Xi": [
          [
            0,
            5,
            "Rød"
          ],
          [
            5,
            8.33,
            "Hvid"
          ],
          [
            10,
            1.66,
            "Rød"
          ]
        ],
        "Yi": [
          10,
          3,
          5
        ],
        "dimensions": [
          "Alkohol",
          "Vand",
          "Farve"
        ],
        "extras": {
          "experimentSuggestionCount": 2
        },
        "hyperparams": {
          "acq_func": "gp_hedge",
          "acq_func_kwargs": {
            "kappa": 1.96,
            "xi": 0.01
          },
          "base_estimator": "GP",
          "n_initial_points": 3
        },
        "space": [
          [
            0,
            10
          ],
          [
            0,
            10
          ],
          [
            "Rød",
            "Hvid"
          ]
        ]
      },
      "pythonVersion": "3.8.5",
      "timeOfExecution": "2021-09-08 21:19:41"
    }
```

### CODE REVIEW

**Comment by sqbl** [comment]
Hi, It's looking good. 
Should we include a call to expected_min already now? I believe that that is one of the missing features which can quiet eaily be added (now or later).
And one question: Aren't we having the datapoints in both root:dataPoints and in root:extras:parameters:Xi now?

**Comment by langdal** [comment]
Yes this PR will result in duplication of datapoints. However, root:extras:parameters represent the parameters used for the actual run while root:datapoints are the ones that will be used next time "run" is pressed. They won't always be the same.

Wrt. expected_min - that should be handled in a separate issue :)

**Review by sqbl — APPROVED** [review]
LGTM

**Comment by sqbl** [comment]
Good points :-)
I got carried away to suggest the expected_minimum call because the old code for that specific feature was deleted in some of the lines... We are working on the behaviour of expected_min but it should have no influence on immediate front end performance. (https://github.com/novonordisk-research/ProcessOptimizer/pull/68)

**Pull request merged**
