### PR TITLE
Update to process_result in optimizer.py

### PR DESCRIPTION
**Pull request by abbl-DTI**
The default call to plot_objective has been updated to include the call for confidence intervals, line 182 in the new version.
Additionally the file has been formatted with 'black'.

### CODE REVIEW

**Comment by langdal** [comment]
Does not work for me with the attached experimen
[78167d7f-081c-4193-a7df-507144908bdc.json.zip](https://github.com/BoostV/process-optimizer-api/files/8519836/78167d7f-081c-4193-a7df-507144908bdc.json.zip)
t

**Comment by langdal** [comment]
@abbl-DTI After a bit more testing it does now work for me on the linked experiment. I can't figure out what made it fail for some runs.

**Comment by abbl-DTI** [comment]
@langdal Is it working as the branch is now? I think I managed to do soft reset of the branch in order to not incorporate the formatting performed by black. But the change in the call to plot_objective was also rolled back.
The check is if there are red bands around the objective plot.
I'll push the updated call to plot_objective in a short will.

**Comment by langdal** [comment]
The current version works yes. A side note - the change log file should never be modified manually. All changes will be overwritten next time the generator is run (which is done with each versioned release). I will squash this PR into only the one commit containing the change to optimizer.py and then approve and merge it, ok?

**Comment by abbl-DTI** [comment]
Sounds great. 
Regarding the Changelog.md, it was updated using the procedure at the end of the README.md. It was unclear to me, what the propper procesure was for just commiting small changes, if this step was necessary.

**Comment by langdal** [comment]
There is no need to update the changelog on each PR - at some point it will be integrated into the automatic build process and until then it is updated with each manual release.

**Review by langdal — APPROVED** [review]

**Pull request merged**
